INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('1', 'kitchen', 2);
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('2', 'internet', 2);
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('3', 'tv', .5);
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('4', 'essentials', '2');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('5', 'airconditioning', '3');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('6', 'washer', '.5');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('7', 'dryer', '.5');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('8', 'free parking on premises', '.5');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('9', 'wifi', '2');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('10', 'cable', '1.5');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('11', 'breakfast', '1');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('12', 'pets-allowed', '.5');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('13', 'family/kid-friendly', '1');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('14', 'smoking allowed', '1');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('15', 'wheelchair-accessable', '1');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('16', 'elevator', '1');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('17', 'indoor fireplace', '.5');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('18', 'buzzer/intercom', '1');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('19', 'doorman', '.5');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('20', 'pool', '3');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('21', 'hot tub', '3');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('22', 'gym', '1');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('23', '24hr -checkin', '.5');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('24', 'hangers', '0.02');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('26', 'iron', '.02');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('27', 'hair dryer', '.02');
INSERT INTO `mybnb`.`ammenities` (`id`, `name`, `vmod`) VALUES ('28', 'laptop friendly workspace', '1');
